"""WebUI command catalog metadata: system, DVM, FFT/MATH, cursor, annotation,
WGEN, and demo commands."""

from __future__ import annotations

from scopes_tool_core.demo import DEMO_FUNCTIONS
from scopes_tool_core.dvm import DVM_MODES
from scopes_tool_core.fft import (
    FFT_DETECTION_TYPES,
    FFT_GATES,
    FFT_OPERATIONS,
    FFT_PHASE_REFERENCES,
    FFT_UNITS,
    FFT_WINDOWS,
)
from scopes_tool_core.math import (
    MATH_COMPOSITE_OPERATIONS,
    MATH_FILTER_OPERATIONS,
    MATH_OPERATIONS,
    MATH_SOURCES,
    MATH_TRANSFORMS,
    MATH_TRANSFORM_SOURCES,
    MATH_TREND_MEASUREMENTS,
    MATH_VISUALIZATION_OPERATIONS,
)
from scopes_tool_core.wgen import WGEN_FUNCTIONS, WGEN_LOADS


FEATURES_COMMANDS = (
    {
        "id": "check-error",
        "category": "System",
        "label": "Error Queue",
        "modes": ("live", "simulate"),
        "fields": (
            {
                "name": "max_reads",
                "type": "integer",
                "minimum": 1,
                "default": 20,
                "label_key": "check-error.max_reads",
                "help_key": "check-error.max_reads",
            },
        ),
    },
    {
        "id": "system-status-byte",
        "category": "System",
        "label": "Instrument Status Summary",
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "system-operation-status",
        "category": "System",
        "label": "Current Operating State",
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "system-clear-status",
        "category": "System",
        "label": "Clear Status and Errors",
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "system-opc",
        "category": "System",
        "label": "Wait for Operation Complete",
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "system-standard-event",
        "category": "System",
        "label": "Event / Error Flags",
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "system-options",
        "category": "System",
        "label": "Installed Options",
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "dvm-enable",
        "category": "DVM",
        "label": "DVM enable",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "enabled", "type": "boolean", "required_if": [{"field": "action", "equals": "set"}], "help_key": "dvm-enable.enabled"},
        ),
    },
    {
        "id": "dvm-source",
        "category": "DVM",
        "label": "DVM source",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "required_if": [{"field": "action", "equals": "set"}], "help_key": "dvm-source.channel"},
        ),
    },
    {
        "id": "dvm-mode",
        "category": "DVM",
        "label": "DVM mode",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "mode", "type": "enum", "options": DVM_MODES, "required_if": [{"field": "action", "equals": "set"}], "help_key": "dvm-mode.mode"},
        ),
    },
    {
        "id": "dvm-auto-range",
        "category": "DVM",
        "label": "DVM auto range",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "enabled", "type": "boolean", "required_if": [{"field": "action", "equals": "set"}], "help_key": "dvm-auto-range.enabled"},
        ),
    },
    {
        "id": "dvm-current",
        "category": "DVM",
        "label": "DVM current reading",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "dvm-query",
        "category": "DVM",
        "label": "DVM state",
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "fft",
        "category": "FFT / MATH",
        "label": "FFT",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "function", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "label_key": "math-function.slot", "option_label": "math-function", "help_key": "math-function.slot"},
            {"name": "source_channel", "type": "integer", "minimum": 1, "maximum": 4, "required_if": [{"field": "action", "equals": "set"}], "help_key": "fft.source_channel"},
            {"name": "units", "type": "enum", "options": FFT_UNITS, "help_key": "fft.units"},
            {"name": "window", "type": "enum", "options": FFT_WINDOWS, "help_key": "fft.window"},
            {"name": "center_hz", "type": "number", "minimum": 0, "help_key": "fft.center_hz"},
            {"name": "span_hz", "type": "number", "exclusive_minimum": 0, "help_key": "fft.span_hz"},
            {
                "name": "fft_operation",
                "type": "enum",
                "options": FFT_OPERATIONS,
                "default": "fft",
                "label_key": "fft.operation",
                "option_label": "fft-operation",
                "help_key": "fft.operation",
            },
            {"name": "start_hz", "type": "number", "label_key": "fft.start_hz", "help_key": "fft.start_hz"},
            {"name": "stop_hz", "type": "number", "label_key": "fft.stop_hz", "help_key": "fft.stop_hz"},
            {
                "name": "gate",
                "type": "enum",
                "options": FFT_GATES,
                "label_key": "fft.gate",
                "option_label": "fft-gate",
                "help_key": "fft.gate",
            },
            {
                "name": "phase_reference",
                "type": "enum",
                "options": FFT_PHASE_REFERENCES,
                "label_key": "fft.phase_reference",
                "option_label": "fft-phase-reference",
                "visible_if": [
                    {"field": "action", "equals": "set"},
                    {"field": "fft_operation", "equals": "fft-phase"},
                ],
                "help_key": "fft.phase_reference",
            },
            {
                "name": "detection_type",
                "type": "enum",
                "options": FFT_DETECTION_TYPES,
                "label_key": "fft.detection_type",
                "option_label": "fft-detection-type",
                "help_key": "fft.detection_type",
            },
            {
                "name": "detection_points",
                "type": "integer",
                "label_key": "fft.detection_points",
                "help_key": "fft.detection_points",
            },
            {"name": "display", "type": "boolean", "label_key": "fft.display", "help_key": "fft.display"},
        ),
    },
    {
        "id": "math-display",
        "category": "FFT / MATH",
        "label": "Math display",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "function", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "label_key": "math-function.slot", "option_label": "math-function", "help_key": "math-function.slot"},
            {"name": "enabled", "type": "boolean", "required_if": [{"field": "action", "equals": "set"}], "help_key": "math-display.enabled"},
        ),
    },
    {
        "id": "math-vertical",
        "category": "FFT / MATH",
        "label": "Math vertical",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "function", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "label_key": "math-function.slot", "option_label": "math-function", "help_key": "math-function.slot"},
            {"name": "scale", "type": "number", "exclusive_minimum": 0, "help_key": "math-vertical.scale"},
            {"name": "range_value", "type": "number", "exclusive_minimum": 0, "help_key": "math-vertical.range_value"},
            {"name": "offset", "type": "number", "help_key": "math-vertical.offset"},
        ),
    },
    {
        "id": "math-operator",
        "category": "FFT / MATH",
        "label": "Math operator",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "function", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "label_key": "math-function.slot", "option_label": "math-function", "help_key": "math-function.slot"},
            {"name": "operation", "type": "enum", "options": MATH_OPERATIONS, "required_if": [{"field": "action", "equals": "set"}], "help_key": "math-operator.operation"},
            {"name": "source1", "type": "enum", "options": MATH_SOURCES, "required_if": [{"field": "action", "equals": "set"}], "help_key": "math-operator.source1"},
            {"name": "source2", "type": "enum", "options": MATH_SOURCES, "required_if": [{"field": "action", "equals": "set"}], "help_key": "math-operator.source2"},
        ),
    },
    {
        "id": "math-transform",
        "category": "FFT / MATH",
        "label": "Math transform",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "function", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "label_key": "math-function.slot", "option_label": "math-function", "help_key": "math-function.slot"},
            {"name": "operation", "type": "enum", "options": MATH_TRANSFORMS, "option_label": "math-transform", "required_if": [{"field": "action", "equals": "set"}], "help_key": "math-transform.operation"},
            {"name": "source", "type": "enum", "options": MATH_TRANSFORM_SOURCES, "required_if": [{"field": "action", "equals": "set"}], "help_key": "advanced-math.source"},
            {"name": "input_offset", "type": "number", "visible_if": [{"field": "action", "equals": "set"}, {"field": "operation", "equals": "integrate"}], "help_key": "math-transform.input_offset"},
            {"name": "gain", "type": "number", "visible_if": [{"field": "action", "equals": "set"}, {"field": "operation", "equals": "linear"}], "help_key": "math-transform.gain"},
            {"name": "linear_offset", "type": "number", "visible_if": [{"field": "action", "equals": "set"}, {"field": "operation", "equals": "linear"}], "help_key": "math-transform.linear_offset"},
        ),
    },
    {
        "id": "math-filter",
        "category": "FFT / MATH",
        "label": "Math filter",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "function", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "label_key": "math-function.slot", "option_label": "math-function", "help_key": "math-function.slot"},
            {"name": "operation", "type": "enum", "options": MATH_FILTER_OPERATIONS, "option_label": "math-filter", "required_if": [{"field": "action", "equals": "set"}], "help_key": "math-filter.operation"},
            {"name": "source", "type": "enum", "options": MATH_TRANSFORM_SOURCES, "required_if": [{"field": "action", "equals": "set"}], "help_key": "advanced-math.source"},
            {"name": "cutoff_hz", "type": "number", "exclusive_minimum": 0, "visible_if": [{"field": "action", "equals": "set"}, {"field": "operation", "in": ["low-pass", "high-pass"]}], "help_key": "math-filter.cutoff_hz"},
            {"name": "average_count", "type": "integer", "minimum": 2, "maximum": 65536, "visible_if": [{"field": "action", "equals": "set"}, {"field": "operation", "equals": "average"}], "help_key": "math-filter.average_count"},
            {"name": "smooth_points", "type": "integer", "minimum": 3, "visible_if": [{"field": "action", "equals": "set"}, {"field": "operation", "equals": "smooth"}], "help_key": "math-filter.smooth_points"},
        ),
    },
    {
        "id": "math-visualization",
        "category": "FFT / MATH",
        "label": "Math visualization",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "function", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "label_key": "math-function.slot", "option_label": "math-function", "help_key": "math-function.slot"},
            {"name": "operation", "type": "enum", "options": MATH_VISUALIZATION_OPERATIONS, "option_label": "math-visualization", "required_if": [{"field": "action", "equals": "set"}], "help_key": "math-visualization.operation"},
            {"name": "source", "type": "enum", "options": MATH_TRANSFORM_SOURCES, "required_if": [{"field": "action", "equals": "set"}], "help_key": "advanced-math.source"},
            {"name": "source2", "type": "enum", "options": MATH_SOURCES, "visible_if": [{"field": "action", "equals": "set"}, {"field": "operation", "equals": "trend"}, {"field": "measurement", "equals": "vratio"}], "required_if": [{"field": "action", "equals": "set"}, {"field": "operation", "equals": "trend"}, {"field": "measurement", "equals": "vratio"}], "help_key": "math-visualization.source2"},
            {"name": "measurement", "type": "enum", "options": MATH_TREND_MEASUREMENTS, "option_label": "math-trend-measurement", "visible_if": [{"field": "action", "equals": "set"}, {"field": "operation", "equals": "trend"}], "required_if": [{"field": "action", "equals": "set"}, {"field": "operation", "equals": "trend"}], "help_key": "math-visualization.measurement"},
            {"name": "measurement_slot", "type": "integer", "minimum": 1, "maximum": 10, "help_key": "math-visualization.measurement_slot"},
        ),
    },
    {
        "id": "math-composite-source",
        "category": "FFT / MATH",
        "label": "Math composite source",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "operation", "type": "enum", "options": MATH_COMPOSITE_OPERATIONS, "required_if": [{"field": "action", "equals": "set"}], "help_key": "math-composite-source.operation"},
            {"name": "source1", "type": "enum", "options": MATH_SOURCES, "required_if": [{"field": "action", "equals": "set"}], "help_key": "math-composite-source.source1"},
            {"name": "source2", "type": "enum", "options": MATH_SOURCES, "required_if": [{"field": "action", "equals": "set"}], "help_key": "math-composite-source.source2"},
        ),
    },
    {
        "id": "math-clear",
        "category": "FFT / MATH",
        "label": "Clear math",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "function", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "label_key": "math-function.slot", "option_label": "math-function", "help_key": "math-function.slot"},
        ),
    },
    {
        "id": "cursor",
        "category": "Cursor",
        "label": "Cursor",
        "modes": ("live", "simulate"),
        "hidden": True,
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set", "off"), "default": "query"},
            {"name": "function", "type": "enum", "options": ("off", "screen", "waveform", "vbars", "hbars"), "option_label": "cursor-function", "visible_if": [{"field": "action", "equals": "set"}], "help_key": "cursor.function"},
            {"name": "source_channel", "type": "integer", "minimum": 1, "maximum": 4, "required_if": [{"field": "action", "equals": "set"}], "visible_if": [{"field": "action", "equals": "set"}], "help_key": "cursor.source_channel"},
            {"name": "x1", "type": "number", "required_if": [{"field": "action", "equals": "set"}], "visible_if": [{"field": "action", "equals": "set"}], "help_key": "cursor.x1"},
            {"name": "x2", "type": "number", "required_if": [{"field": "action", "equals": "set"}], "visible_if": [{"field": "action", "equals": "set"}], "help_key": "cursor.x2"},
            {"name": "y1", "type": "number", "visible_if": [{"field": "action", "equals": "set"}], "help_key": "cursor.y1"},
            {"name": "y2", "type": "number", "visible_if": [{"field": "action", "equals": "set"}], "help_key": "cursor.y2"},
        ),
        "group": "cursor",
        "editor": "cursor",
    },
    {
        "id": "cursor-query",
        "category": "Cursor",
        "label": "Cursor state",
        "modes": ("live", "simulate"),
        "fields": (),
        "editor": "cursor",
    },
    {
        "id": "cursor-set",
        "category": "Cursor",
        "label": "Set cursors",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "function", "type": "enum", "options": ("off", "screen", "waveform", "vbars", "hbars"), "option_label": "cursor-function", "help_key": "cursor.function"},
            {"name": "source_channel", "type": "integer", "minimum": 1, "maximum": 4, "help_key": "cursor.source_channel"},
            {"name": "x1", "type": "number", "help_key": "cursor.x1"},
            {"name": "x2", "type": "number", "help_key": "cursor.x2"},
            {"name": "y1", "type": "number", "help_key": "cursor.y1"},
            {"name": "y2", "type": "number", "help_key": "cursor.y2"},
        ),
        "editor": "cursor",
    },
    {
        "id": "cursor-off",
        "category": "Cursor",
        "label": "Turn off cursors",
        "modes": ("live", "simulate"),
        "fields": (),
        "editor": "cursor",
    },
    {
        "id": "annotation",
        "category": "Annotation",
        "label": "Annotation",
        "modes": ("live", "simulate"),
        "hidden": True,
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set", "on", "off", "clear"), "default": "query"},
            {"name": "slot", "type": "integer", "minimum": 1, "maximum": 10, "default": 1, "label_key": "annotation.slot", "option_label": "annotation-slot", "help_key": "annotation.slot"},
            {"name": "text", "type": "string", "visible_if": [{"field": "action", "equals": "set"}], "help_key": "annotation.text"},
            {"name": "color", "type": "string", "visible_if": [{"field": "action", "equals": "set"}], "help_key": "annotation.color"},
            {"name": "background", "type": "string", "visible_if": [{"field": "action", "equals": "set"}], "help_key": "annotation.background"},
            {"name": "x", "type": "integer", "minimum": 0, "maximum": 800, "visible_if": [{"field": "action", "equals": "set"}], "help_key": "annotation.x"},
            {"name": "y", "type": "integer", "minimum": 0, "maximum": 480, "visible_if": [{"field": "action", "equals": "set"}], "help_key": "annotation.y"},
        ),
        "group": "annotation",
        "editor": "annotation",
    },
    {
        "id": "annotation-query",
        "category": "Annotation",
        "label": "Annotation state",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "slot", "type": "integer", "minimum": 1, "maximum": 10, "default": 1, "label_key": "annotation.slot", "option_label": "annotation-slot", "help_key": "annotation.slot"},
        ),
        "editor": "annotation",
    },
    {
        "id": "annotation-set",
        "category": "Annotation",
        "label": "Set annotation",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "slot", "type": "integer", "minimum": 1, "maximum": 10, "default": 1, "label_key": "annotation.slot", "option_label": "annotation-slot", "help_key": "annotation.slot"},
            {"name": "text", "type": "string", "help_key": "annotation.text"},
            {"name": "color", "type": "enum", "options": ("CH1", "CH2", "CH3", "CH4", "DIG", "MATH", "REF", "MARK", "WHITE", "RED"), "option_label": "annotation-color", "help_key": "annotation.color"},
            {"name": "background", "type": "enum", "options": ("OPAQ", "INV", "TRAN"), "option_label": "annotation-background", "help_key": "annotation.background"},
            {"name": "x", "type": "integer", "minimum": 0, "maximum": 800, "help_key": "annotation.x"},
            {"name": "y", "type": "integer", "minimum": 0, "maximum": 480, "help_key": "annotation.y"},
        ),
        "editor": "annotation",
    },
    {
        "id": "annotation-on",
        "category": "Annotation",
        "label": "Turn on annotation",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "slot", "type": "integer", "minimum": 1, "maximum": 10, "default": 1, "label_key": "annotation.slot", "option_label": "annotation-slot", "help_key": "annotation.slot"},
        ),
        "editor": "annotation",
    },
    {
        "id": "annotation-off",
        "category": "Annotation",
        "label": "Turn off annotation",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "slot", "type": "integer", "minimum": 1, "maximum": 10, "default": 1, "label_key": "annotation.slot", "option_label": "annotation-slot", "help_key": "annotation.slot"},
        ),
        "editor": "annotation",
    },
    {
        "id": "annotation-clear",
        "category": "Annotation",
        "label": "Clear annotation text",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "slot", "type": "integer", "minimum": 1, "maximum": 10, "default": 1, "label_key": "annotation.slot", "option_label": "annotation-slot", "help_key": "annotation.slot"},
        ),
        "editor": "annotation",
    },
    {
        "id": "wgen-query",
        "category": "WGEN",
        "label": "Waveform generator state",
        "modes": ("live", "simulate"),
        "fields": (),
        "editor": "wgen",
    },
    {
        "id": "wgen-output",
        "category": "WGEN",
        "label": "Generator output",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "enabled", "type": "boolean", "required_if": [{"field": "action", "equals": "set"}], "visible_if": [{"field": "action", "equals": "set"}], "help_key": "wgen-output.enabled"},
        ),
        "editor": "wgen",
    },
    {
        "id": "wgen-function",
        "category": "WGEN",
        "label": "Generator function",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "function", "type": "enum", "options": WGEN_FUNCTIONS, "option_label": "wgen-function", "required_if": [{"field": "action", "equals": "set"}], "visible_if": [{"field": "action", "equals": "set"}], "help_key": "wgen-function.function"},
        ),
        "editor": "wgen",
    },
    {
        "id": "wgen-frequency",
        "category": "WGEN",
        "label": "Generator frequency",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "frequency_hz", "type": "number", "required_if": [{"field": "action", "equals": "set"}], "visible_if": [{"field": "action", "equals": "set"}], "help_key": "wgen-frequency.frequency_hz"},
        ),
        "editor": "wgen",
    },
    {
        "id": "wgen-voltage",
        "category": "WGEN",
        "label": "Generator amplitude",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "amplitude", "type": "number", "required_if": [{"field": "action", "equals": "set"}], "visible_if": [{"field": "action", "equals": "set"}], "help_key": "wgen-voltage.amplitude"},
        ),
        "editor": "wgen",
    },
    {
        "id": "wgen-offset",
        "category": "WGEN",
        "label": "Generator offset",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "offset_volts", "type": "number", "required_if": [{"field": "action", "equals": "set"}], "visible_if": [{"field": "action", "equals": "set"}], "help_key": "wgen-offset.offset_volts"},
        ),
        "editor": "wgen",
    },
    {
        "id": "wgen-load",
        "category": "WGEN",
        "label": "Generator load",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "load", "type": "enum", "options": WGEN_LOADS, "option_label": "wgen-load", "required_if": [{"field": "action", "equals": "set"}], "visible_if": [{"field": "action", "equals": "set"}], "help_key": "wgen-load.load"},
        ),
        "editor": "wgen",
    },
    {
        "id": "demo-query",
        "category": "DEMO",
        "label": "Demo Signals state",
        "modes": ("live", "simulate"),
        "fields": (),
        "editor": "demo",
    },
    {
        "id": "demo-output",
        "category": "DEMO",
        "label": "Demo output",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "enabled", "type": "boolean", "required_if": [{"field": "action", "equals": "set"}], "visible_if": [{"field": "action", "equals": "set"}], "help_key": "demo-output.enabled"},
        ),
        "editor": "demo",
    },
    {
        "id": "demo-function",
        "category": "DEMO",
        "label": "Demo function",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "function", "type": "enum", "options": DEMO_FUNCTIONS, "option_label": "demo-function", "required_if": [{"field": "action", "equals": "set"}], "visible_if": [{"field": "action", "equals": "set"}], "help_key": "demo-function.function"},
        ),
        "editor": "demo",
    },
    {
        "id": "demo-phase",
        "category": "DEMO",
        "label": "Demo phase",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "degrees", "type": "number", "minimum": 0, "maximum": 360, "required_if": [{"field": "action", "equals": "set"}], "visible_if": [{"field": "action", "equals": "set"}], "label_key": "demo-phase.degrees", "help_key": "demo-phase.degrees"},
        ),
        "editor": "demo",
    },
)
