"""WebUI command catalog metadata: measurement, capture, reference, and
save/export commands."""

from __future__ import annotations

from scopes_tool_core.measurements import (
    INSTALLABLE_MEASUREMENT_ITEMS,
    MEASUREMENT_WINDOW_CHOICES,
    PAIR_MEASUREMENT_ITEMS,
    SUPPORTED_MEASUREMENT_ITEMS,
)
from scopes_tool_core.save_export import (
    SAVE_IMAGE_FORMATS,
    SAVE_IMAGE_PALETTES,
    SAVE_WAVEFORM_FORMATS,
)


_DIRECT_MEASUREMENT_ITEMS = INSTALLABLE_MEASUREMENT_ITEMS

MEASUREMENT_EXPORT_COMMANDS = (
    {
        "id": "measure",
        "category": "Measurement",
        "label": "Single Measurement",
        "editor": "measurement",
        "modes": ("live", "simulate", "dry-run"),
        "fields": (
            {"name": "item", "type": "enum", "options": SUPPORTED_MEASUREMENT_ITEMS, "default": "vpp", "label_key": "measure.item", "help_key": "measure.item", "help_by_value": {item: f"measure.item.{item}" for item in SUPPORTED_MEASUREMENT_ITEMS}},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "help_key": "measure.channel"},
            {"name": "reference_channel", "type": "integer", "minimum": 1, "maximum": 4, "visible_if": [{"field": "item", "in": ("phase", "delay")}], "required_if": [{"field": "item", "in": ("phase", "delay")}], "help_key": "measure.reference_channel"},
            {"name": "time_s", "type": "number", "visible_if": [{"field": "item", "equals": "y_at_x"}], "required_if": [{"field": "item", "equals": "y_at_x"}], "help_key": "measure.time_s"},
            {"name": "level", "type": "number", "visible_if": [{"field": "item", "equals": "time_at_value"}], "required_if": [{"field": "item", "equals": "time_at_value"}], "help_key": "measure.level"},
            {"name": "slope", "type": "enum", "options": ("positive", "negative"), "default": "positive", "visible_if": [{"field": "item", "in": ("time_at_edge", "time_at_value")}], "option_label": "measure.slope", "help_key": "measure.slope"},
            {"name": "occurrence", "type": "integer", "minimum": 1, "default": 1, "visible_if": [{"field": "item", "in": ("time_at_edge", "time_at_value")}], "label_key": "measure.occurrence", "help_key": "measure.occurrence"},
        ),
    },
    {
        "id": "measure-sweep",
        "category": "Measurement",
        "label": "Multiple Measurements",
        "editor": "measurement",
        "modes": ("live", "simulate", "dry-run"),
        "fields": (
            {"name": "channels", "type": "multi-enum", "options": (1, 2, 3, 4), "serialize": "csv"},
            {"name": "items", "type": "multi-enum", "options": _DIRECT_MEASUREMENT_ITEMS, "serialize": "csv", "default": ("vpp", "frequency", "period", "vrms")},
            {"name": "pairs", "type": "string", "help": "Example: 1:2, 3:4"},
            {"name": "pair_items", "type": "multi-enum", "options": PAIR_MEASUREMENT_ITEMS, "serialize": "csv", "default": ("phase", "delay")},
        ),
    },
    {
        "id": "measure-install",
        "category": "Measurement",
        "label": "Install front-panel measurement",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (
            {
                "name": "source_channel",
                "type": "integer",
                "minimum": 1,
                "maximum": 4,
                "default": 1,
                "required": True,
                "help_key": "measure-install.source_channel",
            },
            {
                "name": "item",
                "type": "enum",
                "options": INSTALLABLE_MEASUREMENT_ITEMS,
                "default": "vpp",
                "required": True,
                "label_key": "measure.item",
                "help_key": "measure-install.item",
            },
        ),
    },
    {
        "id": "measure-results",
        "category": "Measurement",
        "label": "Front-panel measurement results",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "measure-clear",
        "category": "Measurement",
        "label": "Clear measurements",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "measure-menu",
        "category": "Measurement",
        "label": "Open Instrument Measurement Page",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "measure-show",
        "category": "Measurement",
        "label": "Measurement marker display",
        "description": "Set or read whether measurement markers are displayed on the instrument.",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "enabled", "type": "boolean", "option_label": "enabled", "help_key": "measure-show.enabled"},
        ),
    },
    {
        "id": "measurement-statistics",
        "category": "Measurement",
        "label": "Advanced Measurement Statistics",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (
            {
                "name": "action",
                "type": "enum",
                "options": ("query", "set", "reset"),
                "default": "query",
            },
            {
                "name": "mode",
                "type": "enum",
                "options": ("all",),
                "required_if": [{"field": "action", "equals": "set"}],
            },
            {
                "name": "display_enabled",
                "type": "boolean",
                "required_if": [{"field": "action", "equals": "set"}],
                "help_key": "measurement-statistics.display-enabled",
            },
            {
                "name": "max_count_mode",
                "type": "enum",
                "options": ("infinite", "numeric"),
                "required_if": [{"field": "action", "equals": "set"}],
            },
            {
                "name": "max_count",
                "type": "integer",
                "minimum": 2,
                "maximum": 2000,
            },
            {
                "name": "relative_stddev_enabled",
                "type": "boolean",
                "required_if": [{"field": "action", "equals": "set"}],
                "help_key": "measurement-statistics.relative-stddev-enabled",
            },
        ),
    },
    {
        "id": "measure-source",
        "category": "Measurement",
        "label": "Measurement source",
        "modes": ("live", "simulate"),
        "hidden": True,
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "source_channel", "type": "integer", "minimum": 1, "maximum": 4, "required_if": [{"field": "action", "equals": "set"}]},
            {"name": "source2_channel", "type": "integer", "minimum": 1, "maximum": 4},
        ),
    },
    {
        "id": "measure-window",
        "category": "Measurement",
        "label": "Measurement window",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "window", "type": "enum", "options": MEASUREMENT_WINDOW_CHOICES, "required_if": [{"field": "action", "equals": "set"}], "label_key": "measure-window.window", "option_label": "measure-window.window", "help_key": "measure-window.window", "help_by_value": {option: f"measure-window.window.{option}" for option in MEASUREMENT_WINDOW_CHOICES}},
        ),
    },
    {
        "id": "screenshot",
        "category": "Capture",
        "label": "Screenshot",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "background", "type": "enum", "options": ("black", "white"), "default": "black", "help_key": "screenshot.background"},
        ),
    },
    {
        "id": "reference-save",
        "category": "Reference",
        "label": "Save reference waveform",
        "browser_hidden": True,
        "editor": "reference",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "slot", "type": "integer", "minimum": 1, "maximum": 2, "options": (1, 2), "required": True, "label_key": "reference.slot", "option_label": "reference-waveform", "help_key": "reference.slot"},
            {"name": "source_channel", "type": "integer", "minimum": 1, "maximum": 4, "required": True, "help_key": "reference-save.source_channel"},
        ),
    },
    {
        "id": "reference-display",
        "category": "Reference",
        "label": "Reference waveform display",
        "editor": "reference-display",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "slot", "type": "integer", "minimum": 1, "maximum": 2, "options": (1, 2), "default": 1, "label_key": "reference.slot", "option_label": "reference-waveform", "help_key": "reference.slot"},
            {"name": "enabled", "type": "boolean", "required_if": [{"field": "action", "equals": "set"}], "help_key": "reference-display.enabled"},
        ),
    },
    {
        "id": "reference-label",
        "category": "Reference",
        "label": "Reference waveform label",
        "browser_hidden": True,
        "editor": "reference",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "slot", "type": "integer", "minimum": 1, "maximum": 2, "options": (1, 2), "default": 1, "label_key": "reference.slot", "option_label": "reference-waveform", "help_key": "reference.slot"},
            {"name": "label", "type": "string", "required_if": [{"field": "action", "equals": "set"}], "help_key": "reference-label.label"},
        ),
    },
    {
        "id": "reference-clear",
        "category": "Reference",
        "label": "Clear reference waveform",
        "browser_hidden": True,
        "editor": "reference",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "slot", "type": "integer", "minimum": 1, "maximum": 2, "options": (1, 2), "default": 1, "label_key": "reference.slot", "option_label": "reference-waveform", "help_key": "reference.slot"},
        ),
    },
    {
        "id": "reference-query",
        "category": "Reference",
        "label": "Reference waveform state",
        "browser_hidden": True,
        "editor": "reference",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "slot", "type": "integer", "minimum": 1, "maximum": 2, "options": (1, 2), "default": 1, "label_key": "reference.slot", "option_label": "reference-waveform", "help_key": "reference.slot"},
        ),
    },
    {
        "id": "save-pwd",
        "category": "Save / Export",
        "label": "Save path",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "group": "path-filename",
        "editor": "save-export",
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "path", "type": "string", "required_if": [{"field": "action", "equals": "set"}], "label_key": "save-pwd.path", "help_key": "save-pwd.path"},
        ),
    },
    {
        "id": "save-filename",
        "category": "Save / Export",
        "label": "Save filename",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "group": "path-filename",
        "editor": "save-export",
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "name", "type": "string", "required_if": [{"field": "action", "equals": "set"}], "label_key": "save-filename.name", "help_key": "save-filename.name"},
        ),
    },
    {
        "id": "save-image-format",
        "category": "Save / Export",
        "label": "Image save format",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "group": "image",
        "editor": "save-export",
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "format", "type": "enum", "options": SAVE_IMAGE_FORMATS, "required_if": [{"field": "action", "equals": "set"}], "help_key": "save-image-format.format"},
        ),
    },
    {
        "id": "save-image-palette",
        "category": "Save / Export",
        "label": "Image save palette",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "group": "image",
        "editor": "save-export",
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "palette", "type": "enum", "options": SAVE_IMAGE_PALETTES, "required_if": [{"field": "action", "equals": "set"}], "help_key": "save-image-palette.palette"},
        ),
    },
    {
        "id": "save-image-ink-saver",
        "category": "Save / Export",
        "label": "Image ink saver",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "group": "image",
        "editor": "save-export",
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "enabled", "type": "boolean", "required_if": [{"field": "action", "equals": "set"}], "help_key": "save-image-ink-saver.enabled"},
        ),
    },
    {
        "id": "save-image-factors",
        "category": "Save / Export",
        "label": "Image measurement factors",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "group": "image",
        "editor": "save-export",
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "enabled", "type": "boolean", "required_if": [{"field": "action", "equals": "set"}], "help_key": "save-image-factors.enabled"},
        ),
    },
    {
        "id": "save-image",
        "category": "Save / Export",
        "label": "Save image",
        "browser_hidden": False,
        "modes": ("live", "simulate"),
        "editor": "save-export",
        "fields": (
            {"name": "filename", "type": "string", "required": True, "label_key": "save-image.filename", "help_key": "save-image.filename"},
        ),
    },
    {
        "id": "save-waveform-format",
        "category": "Save / Export",
        "label": "Waveform save format",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "group": "waveform",
        "editor": "save-export",
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "format", "type": "enum", "options": SAVE_WAVEFORM_FORMATS, "required_if": [{"field": "action", "equals": "set"}], "help_key": "save-waveform-format.format"},
        ),
    },
    {
        "id": "save-waveform-length",
        "category": "Save / Export",
        "label": "Waveform save length",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "group": "waveform",
        "editor": "save-export",
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "points", "type": "integer", "minimum": 100, "spinner": False, "required_if": [{"field": "action", "equals": "set"}], "help_key": "save-waveform-length.points"},
        ),
    },
    {
        "id": "save-waveform-length-max",
        "category": "Save / Export",
        "label": "Use maximum waveform length",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "group": "waveform",
        "editor": "save-export",
        "fields": (),
    },
    {
        "id": "save-waveform",
        "category": "Save / Export",
        "label": "Save waveform",
        "browser_hidden": False,
        "modes": ("live", "simulate"),
        "editor": "save-export",
        "fields": (
            {"name": "filename", "type": "string", "required": True, "label_key": "save-waveform.filename", "help_key": "save-waveform.filename"},
            {"name": "source_channel", "type": "integer", "minimum": 1, "maximum": 4, "label_key": "source_channel", "option_label": "channel", "help_key": "save-waveform.source_channel"},
        ),
    },
    {
        "id": "setup-save",
        "category": "Save / Export",
        "label": "Save setup",
        "browser_hidden": False,
        "modes": ("live", "simulate"),
        "editor": "save-export",
        "fields": (
            {"name": "target", "type": "enum", "options": ("slot", "file"), "required": True, "option_label": "setup-target", "label_key": "setup.target", "help_key": "setup.target"},
            {"name": "slot", "type": "integer", "options": (0, 1, 2, 3, 4, 5, 6, 7, 8, 9), "visible_if": [{"field": "target", "equals": "slot"}], "required_if": [{"field": "target", "equals": "slot"}], "label_key": "setup.slot", "help_key": "setup.slot"},
            {"name": "file", "type": "string", "visible_if": [{"field": "target", "equals": "file"}], "required_if": [{"field": "target", "equals": "file"}], "label_key": "setup.file", "help_key": "setup.file"},
        ),
    },
    {
        "id": "setup-recall",
        "category": "Save / Export",
        "label": "Recall setup",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "editor": "save-export",
        "fields": (
            {"name": "target", "type": "enum", "options": ("slot", "file"), "required": True, "option_label": "setup-target", "label_key": "setup.target", "help_key": "setup.target"},
            {"name": "slot", "type": "integer", "options": (0, 1, 2, 3, 4, 5, 6, 7, 8, 9), "visible_if": [{"field": "target", "equals": "slot"}], "required_if": [{"field": "target", "equals": "slot"}], "label_key": "setup.slot", "help_key": "setup.slot"},
            {"name": "file", "type": "string", "visible_if": [{"field": "target", "equals": "file"}], "required_if": [{"field": "target", "equals": "file"}], "label_key": "setup.file", "help_key": "setup.file"},
        ),
    },
    {
        "id": "capture",
        "category": "Capture",
        "label": "Waveform capture",
        "modes": ("live", "simulate", "dry-run"),
        "fields": (
            {
                "name": "channels",
                "type": "multi-enum",
                "options": (1, 2, 3, 4),
                "default": (1,),
                "serialize": "csv",
                "required": True,
                "option_label": "channel",
                "label_key": "capture.channels",
                "help_key": "capture.channels",
            },
            {"name": "points", "type": "integer", "options": (1000, 5000, 10000), "default": 1000, "help_key": "capture.points"},
            {"name": "format", "type": "enum", "options": ("byte", "word"), "default": "byte", "help_key": "capture.format"},
        ),
    },
)
