"""WebUI command catalog metadata: device, acquisition, timebase, channel,
and display commands, together with the system, diagnostics, and identity
entries declared in the same original catalog block."""

from __future__ import annotations


CONTROLS_COMMANDS = (
    {
        "id": "live-data-snapshot",
        "category": "Device",
        "label": "Live Data snapshot",
        "hidden": True,
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "system-information-snapshot",
        "category": "System",
        "label": "System Information snapshot",
        "hidden": True,
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "list-resources",
        "category": "Device",
        "label": "List resources",
        "hidden": True,
        "modes": ("live", "simulate", "dry-run"),
        "fields": (
            {"name": "live_only", "type": "boolean", "default": False},
        ),
    },
    {
        "id": "identify",
        "category": "Identity",
        "label": "Read device information",
        "description": "Read instrument identification information",
        "hidden": True,
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "doctor",
        "category": "Diagnostics",
        "label": "Doctor",
        "description": "Read the current instrument diagnostics snapshot",
        "hidden": True,
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "smoke",
        "category": "Diagnostics",
        "label": "Smoke",
        "description": "Run the capture-safe instrument smoke workflow",
        "hidden": True,
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "save_artifacts", "type": "boolean", "default": False},
        ),
    },
    {
        "id": "run",
        "category": "Acquisition",
        "label": "Run",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "single",
        "category": "Acquisition",
        "label": "Single",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "single-wait",
        "category": "Acquisition",
        "label": "Single + Wait",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (
            {
                "name": "trigger_timeout_seconds",
                "type": "number",
                "exclusive_minimum": 0,
                "default": 5.0,
                "required": True,
                "help_key": "single-wait.trigger_timeout_seconds",
            },
            {
                "name": "force_trigger_on_timeout",
                "type": "boolean",
                "default": False,
                "help_key": "single-wait.force_trigger_on_timeout",
            },
            {
                "name": "trigger_poll_interval_ms",
                "type": "integer",
                "minimum": 1,
                "default": 100,
                "required": True,
                "help_key": "single-wait.trigger_poll_interval_ms",
            },
        ),
    },
    {
        "id": "stop-acquisition",
        "category": "Acquisition",
        "label": "Stop",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "force-trigger",
        "category": "Acquisition",
        "label": "Force Trigger",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "acquisition",
        "category": "Acquisition",
        "label": "Acquisition Settings",
        "modes": ("live", "simulate", "dry-run"),
        "fields": (
            {
                "name": "action",
                "type": "enum",
                "options": ("query", "set"),
                "mode_options": {
                    "live": ("query", "set"),
                    "simulate": ("query", "set"),
                    "dry-run": ("query",),
                },
                "default": "query",
            },
            {
                "name": "type",
                "type": "enum",
                "options": ("normal", "average", "high_resolution", "peak"),
                "required_if": [{"field": "action", "equals": "set"}],
                "label_key": "acquisition.type",
                "help_key": "acquisition.type",
                "help_by_value": {
                    "normal": "acquisition.type.normal",
                    "average": "acquisition.type.average",
                    "high_resolution": "acquisition.type.high_resolution",
                    "peak": "acquisition.type.peak",
                },
            },
            {
                "name": "count",
                "type": "integer",
                "minimum": 2,
                "maximum": 65536,
                "visible_if": [{"field": "type", "equals": "average"}],
                "help_key": "acquisition.average_count",
            },
        ),
    },
    {
        "id": "autoscale",
        "category": "Acquisition",
        "label": "Autoscale",
        "description": "Run oscilloscope autoscale; may adjust channel scaling, timebase, and trigger setup.",
        "modes": ("live", "simulate"),
        "fields": (
            {
                "name": "channels",
                "type": "multi-enum",
                "options": (1, 2, 3, 4),
                "serialize": "csv",
                "option_label": "channel",
                "label_key": "autoscale.channels",
                "help_key": "autoscale.channels",
            },
            {
                "name": "acquire_mode",
                "type": "enum",
                "options": ("normal", "current"),
                "label_key": "autoscale.acquire_mode",
                "help_key": "autoscale.acquire_mode",
            },
            {
                "name": "channels_mode",
                "type": "enum",
                "options": ("all", "displayed"),
                "label_key": "autoscale.channels_mode",
                "help_key": "autoscale.channels_mode",
            },
        ),
    },
    {
        "id": "timebase-scale",
        "category": "Timebase",
        "label": "Timebase scale",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {
                "name": "seconds_per_division",
                "type": "number",
                "exclusive_minimum": 0,
                "required_if": [{"field": "action", "equals": "set"}],
                "help_key": "timebase.seconds_per_division",
            },
        ),
    },
    {
        "id": "timebase-position",
        "category": "Timebase",
        "label": "Timebase position",
        "editor": "timebase-position",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {
                "name": "position_seconds",
                "type": "number",
                "required_if": [{"field": "action", "equals": "set"}],
                "help_key": "timebase.position_seconds",
            },
        ),
    },
    {
        "id": "timebase-reference",
        "category": "Timebase",
        "label": "Timebase reference",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {
                "name": "reference",
                "type": "enum",
                "options": ("left", "center", "right"),
                "required_if": [{"field": "action", "equals": "set"}],
                "help_key": "timebase.reference",
            },
        ),
    },
    {
        "id": "channel-display",
        "category": "Channel",
        "label": "Channel display",
        "editor": "channel-display",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "help_key": "channel.target"},
            {"name": "enabled", "type": "boolean", "required_if": [{"field": "action", "equals": "set"}], "help_key": "channel-display.enabled"},
        ),
        "group": "channel-basic",
    },
    {
        "id": "channel-scale",
        "category": "Channel",
        "label": "Channel scale",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "help_key": "channel.target"},
            {
                "name": "volts_per_division",
                "type": "number",
                "exclusive_minimum": 0,
                "required_if": [{"field": "action", "equals": "set"}],
                "help_key": "channel-scale.volts_per_division",
            },
        ),
        "group": "channel-basic",
    },
    {
        "id": "channel-summary",
        "category": "Channel",
        "label": "Read Channel Information",
        "modes": ("live", "simulate"),
        "fields": (),
        "group": "channel-basic",
    },
    {
        "id": "channel-label",
        "category": "Channel",
        "label": "Channel label",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "help_key": "channel.target"},
            {"name": "text", "type": "string", "required_if": [{"field": "action", "equals": "set"}], "help_key": "channel-label.text"},
        ),
        "group": "channel-basic",
    },
    {
        "id": "channel-offset",
        "category": "Channel",
        "label": "Channel offset",
        "editor": "channel-offset",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "help_key": "channel.target"},
            {
                "name": "volts",
                "type": "number",
                "required_if": [{"field": "action", "equals": "set"}],
                "help_key": "channel-offset.volts",
                "label_key": "channel-offset.value",
            },
        ),
        "group": "channel-basic",
    },
    {
        "id": "channel-range",
        "category": "Channel",
        "label": "Channel range",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "help_key": "channel.target"},
            {
                "name": "volts",
                "type": "number",
                "exclusive_minimum": 0,
                "required_if": [{"field": "action", "equals": "set"}],
                "help_key": "channel-range.volts",
                "label_key": "channel-range.value",
            },
        ),
        "group": "channel-basic",
    },
    {
        "id": "channel-coupling",
        "category": "Channel",
        "label": "Channel coupling",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "help_key": "channel.target"},
            {"name": "coupling", "type": "enum", "options": ("ac", "dc"), "required_if": [{"field": "action", "equals": "set"}], "help_key": "channel-coupling.coupling"},
        ),
        "group": "channel-advanced",
    },
    {
        "id": "channel-probe",
        "category": "Channel",
        "label": "Channel probe ratio",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "help_key": "channel.target"},
            {
                "name": "ratio",
                "type": "number",
                "exclusive_minimum": 0,
                "required_if": [{"field": "action", "equals": "set"}],
                "help_key": "channel-probe.ratio",
            },
        ),
        "group": "channel-advanced",
    },
    {
        "id": "channel-bandwidth-limit",
        "category": "Channel",
        "label": "Channel bandwidth limit",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "help_key": "channel.target"},
            {"name": "enabled", "type": "boolean", "required_if": [{"field": "action", "equals": "set"}], "help_key": "channel-bandwidth-limit.enabled"},
        ),
        "group": "channel-advanced",
    },
    {
        "id": "channel-impedance",
        "category": "Channel",
        "label": "Channel impedance",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "help_key": "channel.target"},
            {"name": "impedance", "type": "enum", "options": ("one_meg", "fifty"), "required_if": [{"field": "action", "equals": "set"}], "help_key": "channel-impedance.impedance"},
        ),
        "group": "channel-advanced",
    },
    {
        "id": "channel-invert",
        "category": "Channel",
        "label": "Channel invert",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "help_key": "channel.target"},
            {"name": "enabled", "type": "boolean", "required_if": [{"field": "action", "equals": "set"}], "help_key": "channel-invert.enabled"},
        ),
        "group": "channel-advanced",
    },
    {
        "id": "channel-units",
        "category": "Channel",
        "label": "Channel units",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "help_key": "channel.target"},
            {"name": "units", "type": "enum", "options": ("volt", "amp"), "required_if": [{"field": "action", "equals": "set"}], "help_key": "channel-units.units"},
        ),
        "group": "channel-advanced",
    },
    {
        "id": "channel-vernier",
        "category": "Channel",
        "label": "Channel vernier",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "help_key": "channel.target"},
            {"name": "enabled", "type": "boolean", "required_if": [{"field": "action", "equals": "set"}], "help_key": "channel-vernier.enabled"},
        ),
        "group": "channel-advanced",
    },
    {
        "id": "channel-probe-skew",
        "category": "Channel",
        "label": "Channel probe skew",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "channel", "type": "integer", "minimum": 1, "maximum": 4, "default": 1, "help_key": "channel.target"},
            {"name": "seconds", "type": "number", "minimum": -100e-9, "maximum": 100e-9, "required_if": [{"field": "action", "equals": "set"}], "help_key": "channel-probe-skew.seconds"},
        ),
        "group": "channel-advanced",
    },
    {
        "id": "display-label",
        "category": "Display",
        "label": "Display label",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "enabled", "type": "boolean", "required_if": [{"field": "action", "equals": "set"}], "label_key": "display-label.enabled", "help_key": "display-label.enabled"},
        ),
    },
    {
        "id": "display-clear",
        "category": "Display",
        "label": "Clear display",
        "modes": ("live", "simulate"),
        "fields": (),
    },
    {
        "id": "display-persistence",
        "category": "Display",
        "label": "Display persistence",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "mode", "type": "enum", "options": ("minimum", "infinite", "timed"), "visible_if": [{"field": "action", "equals": "set"}], "required_if": [{"field": "action", "equals": "set"}], "label_key": "display-persistence.mode", "help_key": "display-persistence.mode"},
            {"name": "seconds", "type": "number", "minimum": 0.1, "maximum": 60.0, "visible_if": [{"field": "action", "equals": "set"}, {"field": "mode", "equals": "timed"}], "required_if": [{"field": "action", "equals": "set"}, {"field": "mode", "equals": "timed"}], "label_key": "display-persistence.seconds", "help_key": "display-persistence.seconds"},
        ),
    },
    {
        "id": "display-intensity",
        "category": "Display",
        "label": "Display intensity",
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
            {"name": "value", "type": "integer", "minimum": 0, "maximum": 100, "required_if": [{"field": "action", "equals": "set"}], "label_key": "display-intensity.value", "help_key": "display-intensity.value"},
        ),
    },
    {
        "id": "display-vectors",
        "category": "Display",
        "label": "Display vectors",
        "browser_hidden": True,
        "modes": ("live", "simulate"),
        "fields": (
            {"name": "action", "type": "enum", "options": ("query", "set"), "default": "query"},
        ),
    },
)
