"""Compatibility facade for advanced core controls."""

from __future__ import annotations

from .cursor import (
    CursorState,
    CursorAutoTimebaseResult,
    CursorAutoVerticalResult,
    CursorController,
    cursor_configure_commands,
    cursor_auto_timebase_plan,
    cursor_auto_timebase_dry_run_plan,
    cursor_auto_timebase_json,
    cursor_auto_vertical_plan,
    cursor_auto_vertical_dry_run_plan,
    cursor_auto_vertical_json,
)

from .fft import (
    FFT_OPERATIONS,
    FFT_GATES,
    FFT_PHASE_REFERENCES,
    FFT_DETECTION_TYPES,
    FFTState,
    FFTController,
    fft_configure_commands,
    fft_query_commands,
    fft_advanced_query_commands,
    normalize_fft_units,
    normalize_fft_window,
    normalize_fft_operation,
    parse_fft_operation,
    normalize_fft_gate,
    parse_fft_gate,
    normalize_fft_phase_reference,
    parse_fft_phase_reference,
    normalize_fft_detection_type,
    parse_fft_detection_type,
    validate_fft_detection_points,
    parse_fft_detection_points_response,
)

from .math import (
    MATH_OPERATIONS,
    MATH_SOURCES,
    MATH_TRANSFORM_SOURCES,
    MATH_COMPOSITE_OPERATIONS,
    MATH_TRANSFORMS,
    MATH_FILTER_OPERATIONS,
    MATH_VISUALIZATION_OPERATIONS,
    MATH_TREND_MEASUREMENTS,
    MathDisplayState,
    MathVerticalState,
    MathOperatorState,
    MathTransformState,
    MathCompositeSourceState,
    MathFilterState,
    MathVisualizationState,
    MathController,
    math_display_command,
    math_display_query,
    parse_math_display,
    math_vertical_commands,
    math_vertical_query_commands,
    math_operator_commands,
    math_operator_query_commands,
    math_composite_source_commands,
    math_composite_source_query_commands,
    math_transform_commands,
    math_transform_query_commands,
    math_filter_commands,
    math_filter_query_commands,
    math_visualization_commands,
    math_visualization_query_commands,
    math_clear_command,
    normalize_math_operation,
    normalize_math_source,
    normalize_math_source1,
    parse_math_operation,
    normalize_math_composite_operation,
    parse_math_composite_operation,
    normalize_math_transform,
    parse_math_transform,
    normalize_math_filter_operation,
    parse_math_filter_operation,
    normalize_math_visualization_operation,
    parse_math_visualization_operation,
    normalize_math_trend_measurement,
    parse_math_trend_measurement,
    validate_math_trend_measurement_slot,
    parse_math_trend_measurement_slot,
    validate_math_average_count,
    validate_math_smooth_points,
    parse_math_source,
    parse_math_source1,
    math_function_scpi_prefix,
    validate_function_number,
    validate_finite_number,
    validate_nonnegative,
    validate_positive,
)

from .setup import (
    SetupController,
    autoscale_commands,
    normalize_autoscale_acquire_mode,
    normalize_autoscale_channels_mode,
    setup_save_command,
    setup_recall_command,
    setup_target,
)

from .trigger_holdoff import (
    TRIGGER_HOLDOFF_MIN_SECONDS,
    TRIGGER_HOLDOFF_MAX_SECONDS,
    TriggerHoldoffController,
    trigger_holdoff_command,
    trigger_holdoff_commands,
    trigger_holdoff_query,
    validate_trigger_holdoff,
)
